name: YourInformation
main: lenlenlL6\yourinformation\YourInformation
api: 4.0.0
version: 1.0.0

permissions:
 yourinformation.command.use:
  description: Allow the player use yourinformation command
  default: true